server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /api-docs