version: '3.8'
services:
  database:
    ports:
      - '5434:5432'
    image: postgres:latest
    container_name: 'postgres-payment-service-db'
    volumes:
      - './init:/docker-entrypoint-initdb.d'
    environment:
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0'
      - 'POSTGRES_ROOT_PASSWORD=0'
      - 'POSTGRES_DB=payment_service_db'
      - 'PGDATA=/var/lib/postgresql/data'

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'liga-restaurant-payment-service'
    environment:
      - 'spring.datasource.url=jdbc:postgresql://database:5432/payment_service_db'
    ports:
      - '8081:8081'
    depends_on:
      - database