server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reustarant_service_db
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: waiter-service